project:
  type: website
  output-dir: docs

website: 
  page-navigation: true
  title: "A Case-Study Driven Motivation of Analysis Results Data" 
  site-url: https://joanacmbarros.github.io/ardm-website/
  repo-url: https://github.com/joanacmbarros/ardm-website
  repo-actions: [edit, issue]
  
  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by [ggsurvfit](https://www.danieldsjoberg.com/ggsurvfit-useR-2023/) and [STA210](https://sta210-s22.github.io/website/)."
    
  sidebar:
    logo: "img/logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://joanacmbarros.github.io/ardm-website/
        text: "Website repository"
      - icon: book
        href: https://www.nature.com/articles/s41597-022-01789-2
        text: "Why we should respect analysis results as data"
      - icon: github
        href: https://github.com/joanacmbarros/analysis-results-data-model
        text: "Analysis Results Data Model"
  
    style: "docked"
    search: true
    collapse-level: 3
    border: true
    
    contents:
      - file: index.qmd
        text: "Welcome"
      - file: agenda.qmd
        text: "Agenda"
      - href: related.qmd
        text: Related Work

format:
  html:
    theme: yeti
    css: styles.css
    toc: true


